version: '3'

services:
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - 1234:1234
    environment: 
      - HOST=0.0.0.0
    

  api-gateway:
    build: './api-gateway'
    ports:
      - 3003:3003
    depends_on:
      - buku
      - mahasiswa
      - auth
  

  mahasiswa:
    
    build: ./mahasiswa
    restart: always
    ports:
      - 3000:3000
 
    depends_on: 
      - "mongo"
    
  buku:
    build: ./buku
    restart: always
    ports:
      - 3001:3001
    depends_on: 
      - "mongo"
  
  auth:
    build: ./auth
    restart: always
    ports:
      - 3004:3004
      
  pinjam:
    build: ./pinjam
    restart: always
    ports:
      - 3005:3005
    depends_on: 
      - "mongo"
  
  kembali:
    build: ./kembali
    restart: always
    ports:
      - 3006:3006
    depends_on: 
      - "mongo"
  
  staff:
    build: ./staff
    restart: always
    ports:
      - 3002:3002
    depends_on: 
      - "mongo"

  webperpus:
    build: ./webperpus
    restart: always
    ports:
      - 8080:8080
  

   
volumes:
  mongodb_data_container:

    

 